# Generated by Django 4.1.7 on 2023-02-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='N°')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Región')),
                ('typology', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipología')),
                ('holder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titular')),
                ('investment', models.FloatField(blank=True, null=True, verbose_name='Inversión')),
                ('presentation_date', models.DateField(blank=True, null=True, verbose_name='Fecha Presentación')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado')),
            ],
        ),
    ]
