# Generated by Django 4.1.7 on 2023-02-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion_ambiental', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
